[package]
name = "rs_nes"
version = "0.1.0"
authors = ["Spalynx <Spalynx@gmail.com>"]

readme = "README.md"
keywords = ["nes", "Nintendo", "Entertainment", "System", "Emulator"]
license = "WTFPL"

publish = false

[dependencies]
